package com.haulmont.testtask.clientTier.book;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CustomForm extends VerticalLayout {
    protected Label labelName;
    protected TextField name;
    protected ComboBox generSelect;
    protected ComboBox authorSelect;
    protected Label labelSurname;
    protected ComboBox publisherSelect;
    protected Label labelMiddleName;
    protected TextField year;
    protected Label labelMiddleName1;
    protected TextField city;
    protected Button save;
    protected Button abolish;

    public CustomForm() {
        Design.read(this);
    }
}
