package com.haulmont.testtask.clientTier.menu;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;

import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MenuForm extends HorizontalLayout {
    protected Button mainMenu;
    protected CssLayout menu;
    protected Button authors;
    protected Button genres;
    protected Button books;
    protected Label viewTitle;
    protected CssLayout content;

    public MenuForm() {
        Design.read(this);
    }

}
